spring.application.name=ufc-prediction
server.error.include-message=never
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

ufc.python.project-root=${UFC_PROJECT_ROOT:.}
ufc.python.executable=${PYTHON_EXECUTABLE:}
